language: python
os:
- linux
dist: trusty
sudo: required
python:
- '3.5'
- '3.6'
before install:
- echo "$PATH"
install:
- pip install coveralls
- pip install -r requirements.txt
#- "./install_tools.sh"
#- "./debug_travis.sh"
script:
- python setup.py install
- nosetests --with-coverage --cover-package=clermontpcr tests/ -v
after_success: coveralls
deploy:
  - provider: pypi
    user: NickWaters
    password:
      secure: "QDAAEWnQXISybC+I+ImxS5DPoeA6Z0sl0ExYdjusGc+/HZwiS+xjYnLqM7YHzT3IltjSzCCPxQWzmtGgpdwO1n/QlCxnlajoHCpnLMVHZ8xrXcSmx7J0MfkG4JpbS4MCCf7Q0VLHHHbKtkfiR8HDIeNFYDyOTXT92+Htqo5p/qLoEqAViD3N3QTEhBjdIjMIu7qP69I4t+3+zE2ehMrgdPmnl4w6K/CYTrbQFj8651od7BeJRkFW4GetFI1FR9TgW1/AUNjqPjfqLE15TN1ibTH4o4zW9lWq3Cjo5UQFNNFIwK5XPa2o6Ke3hNrprS4rSQD9EAj1GzM+OcR8OMO5rqRAvVn3tke4i1LEIH9RZdLWp9A8KtnL4tu7ZWrodSIghHiLfV+HEEJAKg5dgyFtvcF2zChC4Wt92BWjQovE0ff/Jg+G1wIOJjk1mnFvWlZcRSgYqdIklJmPwMwOksf6N4n2fLfLo7Euu2OR8VE8BLhN+WyKSLXQ0vv67CZDtSN+8u+YLWeS2O6SFolh5zm9rnuU7c68+eAse0k7xIobM0CItPl5oXjrI8j3GkA6WSFaDxrUJv5P2fg4dxgsN1DV1HOOS1ivt2kWTslt4Qlf7AHdONr10bv09/tKayJdHheYPZUvt7vr7w2KJKW55klgqb+qocXgp5upwp313gzFQwk="
    on:
      tags: true
  - provider: pypi
    user: NickWaters
    server: https://test.pypi.org/legacy
    password:
      secure: "AckVhMoEntU27qNsjg+HdRR2x53VwY4DqDbljFdzt1LnMf63Z/iEspO+g7NE4vkgBVNFQul1fpkiVyTMVWz57KhVLSej1JFoRIeIVpSjzp/NVjWZWUc+p7S9ZLY3vdUWF92mylAx1WmrvNZwQOZFMVtHiZOme4O6H1il16MkcPsf4Lge25/VL8fpYMwh5NQnzf2db9ZfVb9SSAfsnjpc25cA9/xmvMIal26cRwtJzduNoV224oCh8f+r0VWzYonV82r07NZ/i9U0vaDH0auzRti64jaJOHO3MBXX2LF/kE8ACFFrSiDnscFlL3jZ4raIWxyEugBV4hU1Zkz0iSFWX3AH23LtfRvGozuwMC3/kIBPp/lXqjNG+jkBhgaOJPsec3OFUQFuBq1VJIrR4yJP+aSkfz+LfoTmxxda77GfbiEAA1v3onrO8aQiYvxRYd/+/suSXX5k31Vylz4FlIqtnNZfX6xKOasLiEQTDfTMtwHmXRGtRsuJSuEkn1qalMOLSj+WZOoXYS8Zpv+mIai2rjsFCEfpxSdxY5Y4Ck8xMNMXtdXeDVCb1WH6w6FBypgC4wiCUxs/nT25qWGYlapnHz/7NTxjEB7tBmSW47TxMOPae6IgX8SMAcVY4+mrHtNsZpy/dcolebHdTtJA8XqOTxakPa1w3cVy9GlE0DWB6dI="
